const DASHBORD = 'DASHBORD';
const ALL_INVOICE = 'ALL_INVOICE';
const ADD_ITEM = 'ADD_ITEM';
const CREATE_INVOICE_GOLD = 'CREATE_INVOICE_GOLD';
const CREATE_INVOICE_SILVER = 'CREATE_INVOICE_SILVER';
const CREATE_INVOICE_DIAMOND = 'CREATE_INVOICE_DIAMOND';
const VIEW_INVOICE_GOLD = 'VIEW_INVOICE_GOLD';
const VIEW_ESTEEMED_GOLD = 'VIEW_ESTEEMED_GOLD';
const BACK_GOLD = 'BACK_GOLD';
const VIEW_INVOICE_DIAMOND = 'VIEW_INVOICE_DIAMOND';
const VIEW_BOS_DIAMOND = 'VIEW_BOS_DIAMOND';
const BACK_DIAMOND = 'BACK_DIAMOND';
const VIEW_INVOICE = 'VIEW_INVOICE';
const VIEW_BOS_GOLD = 'VIEW_BOS_GOLD';
const VIEW_INVOICE_SILVER = 'VIEW_INVOICE_SILVER';
const VIEW_ESTEEMED_SILVER = 'VIEW_ESTEEMED_SILVER';
const VIEW_BOS_SILVER = 'VIEW_BOS_SILVER';
const BACK_SILVER = 'BACK_SILVER';
const VIEW_ESTEEMED_DIAMOND = 'VIEW_ESTEEMED_DIAMOND';
const COSTUME = 'COSTUME';
const COSTUME_INVOICE = 'COSTUME_INVOICE';
export {
  DASHBORD,
  ALL_INVOICE,
  ADD_ITEM,
  CREATE_INVOICE_GOLD,
  CREATE_INVOICE_SILVER,
  CREATE_INVOICE_DIAMOND,
  VIEW_INVOICE_GOLD,
  VIEW_ESTEEMED_GOLD,
  BACK_GOLD,
  VIEW_INVOICE_DIAMOND,
  VIEW_BOS_DIAMOND,
  BACK_DIAMOND,
  VIEW_INVOICE,
  VIEW_BOS_GOLD,
  VIEW_INVOICE_SILVER,
  VIEW_ESTEEMED_SILVER,
  VIEW_BOS_SILVER,
  BACK_SILVER,
  VIEW_ESTEEMED_DIAMOND,
  COSTUME,
  COSTUME_INVOICE,
};
